services:
  trinity-hero-web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
